/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sisGestion.vistaGui;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import sisGestion.controller.DepartmentController;
import sisGestion.model.Department;

public class DialogoEditarDepartamento extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogoEditarDepartamento.class.getName());
    private final DepartmentController departmentController;
    private final Department departamentoAEditar;
    private JTextField txtNuevoNombre;

    public DialogoEditarDepartamento(JFrame parent, boolean modal, DepartmentController controller, Department depto) {
        super(parent, modal);
        this.departmentController = controller;
        this.departamentoAEditar = depto;

        // --- Configuración básica de la ventana ---
        setTitle("Editar Departamento");
        setSize(400, 160);
        setLayout(new BorderLayout());
        setLocationRelativeTo(parent);

        // --- INICIO: Construcción de la Interfaz Visual ---
        
        // Panel para el formulario (donde va el campo de texto)
        JPanel formPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 20));
        formPanel.setBorder(new EmptyBorder(10, 10, 10, 10)); // Margen
        formPanel.add(new JLabel("Nuevo nombre:"));
        
        // Creamos el campo de texto y lo rellenamos con el nombre actual del departamento
        txtNuevoNombre = new JTextField(departamentoAEditar.getName(), 20); 
        formPanel.add(txtNuevoNombre);
        
        // Añadimos el panel del formulario al centro de la ventana
        add(formPanel, BorderLayout.CENTER);

        // Panel para los botones (Guardar y Cancelar)
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnGuardar = new JButton("Guardar");
        JButton btnCancelar = new JButton("Cancelar");
        buttonPanel.add(btnGuardar);
        buttonPanel.add(btnCancelar);
        
        // Añadimos el panel de botones a la parte de abajo de la ventana
        add(buttonPanel, BorderLayout.SOUTH);

        // --- FIN: Construcción de la Interfaz Visual ---

        // --- Lógica de los botones ---
        btnGuardar.addActionListener(e -> guardarCambios());
        btnCancelar.addActionListener(e -> dispose()); // dispose() simplemente cierra la ventana
    }

    /**
     * Método que se ejecuta al presionar "Guardar".
     */
    private void guardarCambios() {
        String nuevoNombre = txtNuevoNombre.getText().trim();
        
        if (nuevoNombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Llamamos al controlador para que actualice el nombre
        departmentController.actualizarDepartamento(departamentoAEditar.getCode(), nuevoNombre);
        
        // Cerramos la ventana
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
